<a href="https://colab.research.google.com/github/NijatLmmdv/8-Queens-Problem-OR-/blob/main/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#import main library
import numpy as np

In [6]:
#give numbers to meals
state = {
    0 : "Burger",
    1 : "Pizza",
    2 : "Hotdog"
}
state

{0: 'Burger', 1: 'Pizza', 2: 'Hotdog'}

In [7]:
#make array 
A = np.array([[0.2,0.6,0.2],
              [0.3,0.0,0.7],
              [0.5,0.0,0.5]
              ])
A

array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

In [25]:
#random walk on markov chain
n = 15 #number of steps
start_state = 0 #which state begin
print(state[start_state], " ",end="") #print name of state
prev_state = start_state 

while n-1:
    curr_state = np.random.choice([0, 1, 2],p=A[prev_state])
    print(state[curr_state], " ",end="")
    prev_state = curr_state
    n-=1
#print("stop")


Burger  Pizza  Hotdog  Hotdog  Hotdog  Hotdog  Burger  Hotdog  Hotdog  Hotdog  Hotdog  Hotdog  Burger  Pizza  Hotdog  

In [26]:
steps = 10**6
start_state = 0
pi = np.array([0,0,0])
pi[start_state] = 1
prev_state = start_state


i=0
while i<steps:
  curr_state = np.random.choice([0,1,2],p=A[prev_state])
  pi[curr_state]+=1
  prev_state = curr_state
  i +=1

print("π =",pi/steps)

π = [0.35211  0.211003 0.436888]


In [27]:
steps = 10**3
A_n = A

i=0
while i<steps:
    A_n =  np.matmul(A_n, A)
    i+=1

print("A^n = \n", A_n, "\n")
print("π = ", A_n[0])

A^n = 
 [[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]] 

π =  [0.35211268 0.21126761 0.43661972]


In [28]:
import scipy.linalg
values, left = scipy.linalg.eig(A, right = False, left = True)

print("left eigen vectors = \n", left, "\n")
print("eigen values = \n", values)

left eigen vectors = 
 [[-0.58746336+0.j          0.16984156+0.35355339j  0.16984156-0.35355339j]
 [-0.35247801+0.j         -0.67936622+0.j         -0.67936622-0.j        ]
 [-0.72845456+0.j          0.50952467-0.35355339j  0.50952467+0.35355339j]] 

eigen values = 
 [ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]


In [29]:
pi = left[:,0]
pi_normalized = [(x/np.sum(pi)).real for x in pi]
pi_normalized


[0.3521126760563379, 0.21126760563380304, 0.4366197183098591]

In [30]:
def find_prob(seq, A, pi):
    start_state = seq[0]
    prob = pi[start_state]
    prev_state, curr_state = start_state, start_state
    for i in range(1, len(seq)):
        curr_state = seq[i]
        prob *= A[prev_state][curr_state]
        prev_state = curr_state
    return prob

print(find_prob([1, 2, 2, 0], A, pi_normalized))

0.03697183098591553
